version: '3'

services:
  db:
    image: mysql
    ports:
      - "3306:3306" # REMOVE BEFORE DEPLOY, USE FOR DEV ONLY #
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "application"
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    links:
      - db
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: