version: "3.7"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "application"
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "db:3306", "--"]
    restart: always
    links:
      - db
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: