version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "application"
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: